[package]
name = "piper"
version = "0.1.0"
edition = "2021"

[dependencies]
repl = { path = "../repl/" }
filerunner = { path = "../filerunner//" }
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features =[ "env-filter"]}
